language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit -v -c tests/travis/travis.$DB.xml

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
    - php: 7.0       # PHP 7 requires PHPUnit 5, work needed to support the later

sudo: false
